### ISSUE TITLE
Two Extractly same rules by RulefitClassifier

### ISSUE THREAD

**Issue by Yannahhh** [csinva/imodels#80] opened 2022-01-25 02:25 UTC
Hello~

When I use the RulefitClassifier, it will return two exactly same rules but with different coef, whether the inherent structures didn't aggregate the rules? I have tried to use the Rulefit directly, and it seems that it doesn't have the similar problem~

The following image is part of my result
<img width="613" alt="image" src="https://user-images.githubusercontent.com/32149104/150899583-b71bc405-5333-45f3-b849-208305549113.png">

**Comment by keyan3** [comment] 2022-01-25 04:03
Hi, thanks for bringing this to our attention. Can you provide more details on the code used to produce this result?

**Comment by Yannahhh** [comment] 2022-01-25 04:13
Thanks for your reply, should I provide my data also?

>  features = X.columns
>   X = X.values
>   rulefit = RuleFitClassifier(random_state=2022, tree_size=3, exp_rand_tree_size=False)
>   rulefit.fit(X, y, feature_names=features)
>   preds = rulefit.predict(X)
>   accuracy = round(metrics.accuracy_score(y, preds), 2)
>   rules = rulefit.get_rules()
>   rules = rules[rules.coef != 0].sort_values("coef", ascending=False)

**Comment by keyan3** [comment] 2022-01-29 01:01
No need to provide the data — this is caused by a bug in the process of checking for duplicate rules ([https://github.com/csinva/imodels/blob/master/imodels/util/extract.py#L97-L107](url)). We will have it fixed shortly!

**Comment by keyan3** [comment] 2022-02-08 19:59
Was fixed in #87

**Closed by keyan3** 2022-02-08 19:59 UTC
Labels: bug
